config-version: 2

name: 'github'
version: '0.2.0'

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
  github:
    +materialized: view
    intermediate:
      +materialized: ephemeral

vars:
  github_source:
    github_database: raw
    github_schema: raw_fivetran_github

#vars:
#  github:
#    issue_assignee: "{{ ref('stg_github_issue_assignee') }}"
#    issue_closed_history: "{{ ref('stg_github_issue_closed_history') }}"
#    issue_comment: "{{ ref('stg_github_issue_comment') }}"
#    issue_label: "{{ ref('stg_github_issue_label') }}"
#    issue_merged: "{{ ref('stg_github_issue_merged') }}"
#    issue: "{{ ref('stg_github_issue') }}"
#    pull_request_review: "{{ ref('stg_github_pull_request_review') }}"
#    pull_request: "{{ ref('stg_github_pull_request') }}"
#    repository: "{{ ref('stg_github_repository') }}"
#    requested_reviewer_history: "{{ ref('stg_github_requested_reviewer_history') }}"
#    user: "{{ ref('stg_github_user') }}"
