name: 'github_integration_tests'
version: '0.2.0'
config-version: 2

profile: 'integration_tests'

clean-targets:
  - 'target'
  - 'dbt_modules'

vars:
  github_source:
    github_database: raw
    github_schema: raw_fivetran_github
